set_property PACKAGE_PIN T3 [get_ports A]
set_property PACKAGE_PIN U3 [get_ports B]
set_property PACKAGE_PIN T4 [get_ports Cin]
set_property PACKAGE_PIN R1 [get_ports Cout]
set_property PACKAGE_PIN P2 [get_ports Sum]
set_property IOSTANDARD LVCMOS18 [get_ports A]
set_property IOSTANDARD LVCMOS18 [get_ports B]
set_property IOSTANDARD LVCMOS18 [get_ports Cin]
set_property IOSTANDARD LVCMOS18 [get_ports Cout]
set_property IOSTANDARD LVCMOS18 [get_ports Sum]
set_property PULLDOWN true [get_ports A]
set_property PULLDOWN true [get_ports B]
set_property PULLDOWN true [get_ports Cin]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
